#!/bin/bash

. $HOME/.config/wayland-build-tools/wl_defines.sh

# TODO: Check if tree already exists first
# TODO: Bail if errors
# TODO: Log output


clone_or_update() {
	repo=$1
	if [ -z "$2" ]
  	then
		dest=$(basename $repo)
	else
		dest=$2
	fi

	cd ${WLROOT}
	if [ $? != 0 ]; then
		echo "Error: Could not cd to ${WLROOT}.  Does it exist?"
        exit 1
	fi
	echo
	echo $dest
	if [ ! -d ${dest} ]; then
		git clone ${repo} ${dest}
		if [ $? != 0 ]; then
			echo "Error: Could not clone repository"
			exit 1
		fi
	fi
	cd ${dest}
	if [ -z "$3" ]
  	then
		git checkout master
	else
		git checkout $3
	fi

	if [ $? != 0 ]; then
		echo "Error: Problem checking out master"
		exit 1
	fi
	git pull
	if [ $? != 0 ]; then
		echo "Error: Could not pull from upstream"
		exit 1
	fi
	cd ${WLROOT}
}

clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxau.git libxau
clone_or_update git://anongit.freedesktop.org/wayland/wayland wayland 1.14
clone_or_update git://anongit.freedesktop.org/git/mesa/drm
clone_or_update git://anongit.freedesktop.org/xcb/proto
clone_or_update git://anongit.freedesktop.org/xorg/util/macros
clone_or_update git://anongit.freedesktop.org/xcb/libxcb
clone_or_update git://anongit.freedesktop.org/xorg/lib/libxshmfence
clone_or_update https://github.com/xkbcommon/libxkbcommon.git libxkbcommon
clone_or_update git://anongit.freedesktop.org/mesa/mesa mesa 17.2
clone_or_update git://anongit.freedesktop.org/pixman
clone_or_update git://anongit.freedesktop.org/cairo
clone_or_update git://git.sv.gnu.org/libunwind
clone_or_update git://anongit.freedesktop.org/libevdev
#clone_or_update https://gitlab.freedesktop.org/wayland/wayland-protocols.git wayland-protocols 1.21
clone_or_update https://github.com/linuxwacom/libwacom.git libwacom master
clone_or_update git://anongit.freedesktop.org/wayland/libinput
clone_or_update git://anongit.freedesktop.org/wayland/weston
clone_or_update https://github.com/libcheck/check.git check master

if [ ${INCLUDE_XWAYLAND} ]; then
	if [ ${WL_BITS} = "32" ]; then
		clone_or_update git://anongit.freedesktop.org/xorg/lib/libxtrans
	fi
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libx11.git libx11 stable
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxdmcp.git libxdmcp master
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libfontenc.git libfontenc master
	clone_or_update https://gitlab.freedesktop.org/xorg/app/xkbcomp.git xkbcomp master
	clone_or_update https://gitlab.freedesktop.org/xorg/font/util.git util master
	clone_or_update https://github.com/anholt/libepoxy.git libepoxy
	clone_or_update https://gitlab.freedesktop.org/xorg/proto/xorgproto.git xorgproto
	clone_or_update git://anongit.freedesktop.org/xorg/lib/libxtrans
	clone_or_update git://anongit.freedesktop.org/xorg/lib/libxkbfile
	clone_or_update git://anongit.freedesktop.org/xorg/lib/libXfont
	clone_or_update git://anongit.freedesktop.org/xorg/xserver xserver xwayland-21.1
fi
