#!/bin/bash

. $HOME/.config/wayland-build-tools/wl_defines.sh

# TODO: Check if tree already exists first
# TODO: Bail if errors
# TODO: Log output


clone_or_update() {
	repo=$1
	if [ -z "$2" ]
  	then
		dest=$(basename $repo)
	else
		dest=$2
	fi

	cd ${WLROOT}
	if [ $? != 0 ]; then
		echo "Error: Could not cd to ${WLROOT}.  Does it exist?"
        exit 1
	fi
	echo
	echo $dest
	if [ ! -d ${dest} ]; then
		git clone ${repo} ${dest}
		if [ $? != 0 ]; then
			echo "Error: Could not clone repository"
			exit 1
		fi
	fi
	cd ${dest}
	if [ -z "$3" ]
  	then
		git checkout master
	else
		git checkout $3
	fi

	if [ $? != 0 ]; then
		echo "Error: Problem checking out master"
		exit 1
	fi
	git pull origin $3
	if [ $? != 0 ]; then
		echo "Error: Could not pull from upstream"
		exit 1
	fi
	cd ${WLROOT}
}

tarfile_download_extract() {
	url=$1
	folder=$2
	filename="$(basename -- $url)"
	extension="${filename##*.}"
	echo $extension
	cd ${WLROOT}
	if [ $? != 0 ]; then
		echo "Error: Could not cd to ${WLROOT}.  Does it exist?"
        exit 1
	fi
	echo
	if test -d "$folder"; then
    	echo "folder ./$folder exists."
	else
		echo "filename ${filename}"
		mkdir $folder
		if [[ $extension == "xz" ]]; then
			echo "wget -c $url -O - | tar -Jx -C $folder --strip-components=1"
			wget -c $url -O - | tar -Jx -C $folder --strip-components=1
		elif [[ $extension == "gz" ]]; then
			echo "wget -c $url -O - | tar -xz -C $folder --strip-components=1"
			wget -c $url -O - | tar -xz -C $folder --strip-components=1
		fi
	fi
	
	if [ $? != 0 ]; then
		echo "Error: Problem downloading file / extracting archive"
		rm -r $folder
		exit 1
	fi
	

	cd ${WLROOT}

}
tarfile_download_extract https://github.com/unicode-org/icu/archive/refs/tags/release-72-1.tar.gz libicu
clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxau.git libxau
clone_or_update git://anongit.freedesktop.org/wayland/wayland wayland eb1339edd398b9f5328816931e585db4229aa132
clone_or_update git://anongit.freedesktop.org/git/mesa/drm drm 56f81e6776c1c100c3f627b2c1feb9dcae2aad3c
clone_or_update git://anongit.freedesktop.org/xcb/proto
clone_or_update git://anongit.freedesktop.org/xorg/util/macros
clone_or_update git://anongit.freedesktop.org/xcb/libxcb
clone_or_update git://anongit.freedesktop.org/xorg/lib/libxshmfence
tarfile_download_extract https://xkbcommon.org/download/libxkbcommon-1.4.1.tar.xz libxkbcommon
clone_or_update git://anongit.freedesktop.org/mesa/mesa mesa 78c96ae5b6197c66c681b1825411d7a05f85f0a6
clone_or_update git://anongit.freedesktop.org/pixman
clone_or_update git://anongit.freedesktop.org/cairo cairo 1.16
tarfile_download_extract https://github.com/libunwind/libunwind/releases/download/v1.6.2/libunwind-1.6.2.tar.gz libunwind
clone_or_update git://anongit.freedesktop.org/libevdev
clone_or_update https://gitlab.freedesktop.org/wayland/wayland-protocols.git wayland-protocols 630fb089103a1d0eab1a684b853ab5c4d2b252aa
tarfile_download_extract https://github.com/linuxwacom/libwacom/archive/refs/tags/libwacom-2.5.0.tar.gz libwacom
clone_or_update git://anongit.freedesktop.org/wayland/libinput
clone_or_update git://anongit.freedesktop.org/wayland/weston
clone_or_update https://github.com/libcheck/check.git check master
clone_or_update https://github.com/intel/libva.git libva v2.17-branch
clone_or_update https://gitlab.gnome.org/GNOME/pango.git pango 3d3f165e77178b630d7dc2b733e64af513c99f5f

if [ ${INCLUDE_XWAYLAND} ]; then
	if [ ${WL_BITS} = "32" ]; then
		clone_or_update git://anongit.freedesktop.org/xorg/lib/libxtrans
	fi
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libx11.git libx11 48487c4b9028e9eec5371742f51e1d64c2e17296
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxext.git libxext 67e82cc395f44faddd83ec3d0d21624fe91c6fc0
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxfixes.git libxfixes 6fe3bd64dd82f704ed91478acb4c99ab5c00be16
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxxf86vm.git libxxf86vm 7fe2d41f164d3015216c1079cc7fbce1eea90c98
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxrandr.git libxrandr 3387129532899eaeee3477a2d92fa662d7292a84
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxrender.git libxrender e5e23272394c90731debd7e18dd167e8c25b5c15
	clone_or_update https://github.com/linux-pam/linux-pam.git linux-pam 
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxcursor.git libxcursor b84b5d100f193fda0630c4d6fa889cd3e05ca033
	clone_or_update https://chromium.googlesource.com/webm/libwebp libwebp 1.3.0
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libxdmcp.git libxdmcp master
	clone_or_update https://gitlab.freedesktop.org/xorg/lib/libfontenc.git libfontenc master
	clone_or_update https://gitlab.freedesktop.org/xorg/app/xkbcomp.git xkbcomp master
	clone_or_update https://gitlab.freedesktop.org/xorg/font/util.git util master
	clone_or_update https://github.com/anholt/libepoxy.git libepoxy
	clone_or_update https://gitlab.freedesktop.org/xorg/proto/xorgproto.git xorgproto
	clone_or_update git://anongit.freedesktop.org/xorg/lib/libxtrans
	clone_or_update git://anongit.freedesktop.org/xorg/lib/libxkbfile
	clone_or_update git://anongit.freedesktop.org/xorg/lib/libXfont
	clone_or_update git://anongit.freedesktop.org/xorg/xserver xserver xwayland-21.1
fi
